### ISSUE TITLE
code in pv.doSetScore

### ISSUE THREAD

**Issue by TessaTi** [bioc/DiffBind#1]
Dear all, 

Thank you for the repository. I was looking at the function: 
**pv.doSetScore** and noticed these part to be repeated and do not get why (code from line 999 to 1004):

if(score == PV_SCORE_RPKM) {
          pv$binding[,colnum] <- pv$peaks[[i]]$RPKM	
}   		
if(score == PV_SCORE_RPKM) {
          pv$binding[,colnum] <- pv$peaks[[i]]$RPKM	
}

Thank you for your time and consideration. 
Kind regards

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of Bioconductor, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
